name: 'Get Repository Cache'

runs:
  using: "composite"
  steps:
    - id: restore-cache
      name: Restore Cache
      uses: actions/download-artifact@v4
      with:
        name: ${{ runner.os }}-bun-${{ hashFiles('bun.lockb') }}
        merge-multiple: true
        path: |
          ~/.bun
          **/node_modules
          .nx/cache
