general:
  visibility: public
  template-repository: false
  sign-off-web-commits: true
  social-preview-image: ""
  default_branch: next
  features:
    wiki: false
    pages: false
    issues: true
    projects: false
    preserve: true
    sponserships: false
  pull_requests:
    merge_commits: "PULL_REQUEST_TITLE"
  # https://github.com/repository-settings/app
  # https://github.com/github/safe-settings
