name: 'Get Repository Cache'

runs:
  using: "composite"
  steps:    
    - id: restore-cache
      name: Restore Repository Cache
      uses: actions/cache/restore@v4
      with:
        path: |
          ~/.bun
          ./node_modules
        key: ${{ runner.OS }}-bun-${{ hashFiles('bun.lockb') }}
        restore-keys: ${{ runner.OS }}-bun
