name: 'Setup Repository'

inputs:
  isSuccess:
    description: 'Whether the status is success'
    required: true
  successMsg:
    description: 'The description of the status when it is success'
    required: true
  failureMsg:
    description: 'The description of the status when it is failure'
    required: true

runs:
  using: "composite"
  steps:    
    - name: Set status
        uses: actions/github-script@v7
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          script: |
            const state = ${{ inputs.isSuccess }};
            github.rest.repos.createCommitStatus({
              owner: context.repo.owner,
              repo: context.repo.repo,
              sha: context.payload.pull_request.head.sha,
              state: state ? 'success' : 'failure',
              context: 'Lint Code',
              description: state ? '${{ inputs.successDescription }}' : '${{ inputs.failureDescription }}'
            })
