name: 'Setup Repository'

runs:
  using: "composite"
  steps:    
    # Using GitHub Artifacts results in permission loss. Identify if this is a problem.
    - id: restore-cache
      name: Restore Cache
      uses: actions/download-artifact@v4
      with:
        name: ${{ runner.os }}-bun-${{ hashFiles('bun.lockb') }}
        merge-multiple: true
        path: |
          ~/.bun
          **/node_modules
          .nx/cache

    - name: Install Bun
      if: steps.restore-cache.outputs.artifact-id == ''
      uses: oven-sh/setup-bun@v2
      with:
        bun-version: latest

    - name: Upgrade Bun
      if: steps.restore-cache.outputs.artifact-id != ''
      run: bun upgrade
      shell: bash
      # Always running on the latest version is not a good idea. Changes to bun shall directly affect the pipeline.
      # We will revisit this during migration to Deno 2 LTS
    
    - name: Install dependencies
      run: bun install
      shell: bash
    
    # - name: Run postinstall scripts
    #   run: bun pm trust --all
    #   continue-on-error: true

    - name: Save Cache (node_modules)
      uses: actions/upload-artifact@v4
      with:
        name: ${{ runner.os }}-bun-${{ hashFiles('bun.lockb') }}
        overwrite: true
        retention-days: 10
        path: |
          ~/.bun
          **/node_modules
          .nx/cache
