export const ServerDbList = [
	{ name: 'AWS Aurora', value: 'aws-aurora' },
	{ name: 'AWS DynamoDB', value: 'aws-dynamodb' },
	{ name: 'AWS RDS', value: 'aws-rds' },
	{ name: 'CockroachDB', value: 'cockroachdb' },
	{ name: 'Cloudflare D1', value: 'cloudflare-d1' },
	{ name: 'Cloudflare R2', value: 'cloudflare-r2' },
	{ name: 'FaunaDB', value: 'faunadb' },
	{ name: 'GCP Bigtable', value: 'google-cloud-bigtable' },
	{ name: 'GCP Firestore', value: 'google-cloud-firestore' },
	{ name: 'GCP Spanner', value: 'google-cloud-spanner' },
	{ name: 'GCP Cloud SQL', value: 'google-cloud-sql' },
	{ name: 'MySQL', value: 'mysql' },
	{ name: 'MongoDB', value: 'mongodb' },
	{ name: 'Neo4j', value: 'neo4j' },
	{ name: 'NeonDB', value: 'neondb' },
	{ name: 'PostgreSQL', value: 'postgresql' },
	{ name: 'Supabase', value: 'supabase' },
];
