name: Code Quality

on:
  push:
    branches: [stable, staging]
  pull_request:
    branches: [stable, staging]

jobs:
  code-quality:
    name: Code Quality
    runs-on: ubuntu-latest
    timeout-minutes: 10
    permissions:
      contents: read
      id-token: write # needed for provenance data generation
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          
      - name: Setup
        uses: AdityaBorkar/letsync/.github/workflows/init.yml
      
      - name: Format, Lint, Organize Imports and Save
        shell: bash
        run: |
          bun run format
          bun run lint:code
          bun run lint:knip
          bun run lint:cspell
          bun run lint:markdownlint
          git add .
          git commit -m "refactor: lint, format, organize-imports"

      - name: Build Packages
        shell: bash
        run: |
          bun run check-types
          bun run build
        
      - name: Release
        shell: bash
        run: |
          git add .
          git commit -m "chore(release): {version}"
          bun nx release
