name: Publish Release

on:
  push:
    tags:
      - v*.*.*

jobs:
  publish:
    name: Publish
    runs-on: ubuntu-latest
    timeout-minutes: 10
    permissions:
      contents: read
      id-token: write # needed for provenance data generation
    steps:
      - name: Setup
        uses: AdityaBorkar/letsync/.github/workflows/init.yml
      
      - name: Print Environment Info
        run: bun nx report
        shell: bash

      # - name: Publish packages
      #   run: bun nx release publish
      #   shell: bash
      #   env:
      #     NODE_AUTH_TOKEN: ${{ secrets.NPM_ACCESS_TOKEN }}
      #     NPM_CONFIG_PROVENANCE: true
