name: Publish Packages and Deployments

on:
  push:
    tags:
      - v*.*.*

jobs:
  publish:
    name: Publish Job
    runs-on: ubuntu-latest
    timeout-minutes: 10
    permissions:
      contents: read
      id-token: write # needed for provenance data generation
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup
        uses: ./.github/workflows/init.yaml
       
      - name: Print Environment Info
        run: bun nx report

      # - name: Publish packages
      #   run: bun nx release publish
      #   shell: bash
      #   env:
      #     NODE_AUTH_TOKEN: ${{ secrets.NPM_ACCESS_TOKEN }}
      #     NPM_CONFIG_PROVENANCE: true
