name: Release

on:
  release:
    types: [published]
      
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  issues: write
  statuses: write
  contents: write
  id-token: write
  pull-requests: write
  packages: write
  deployments: write

jobs:
  release:
    if: github.event.release.tag_name == 'trigger.release'
    name: Release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          fetch-tags: true
      - uses: oven-sh/setup-bun@v2
      - run: bun install
      - id: release
        continue-on-error: true
        run: bun ./scripts/release.ts tag=trigger.release type=${{ github.event.release.target_commitish }}
      - run: echo "${{ steps.release.outcome }}" >> $GITHUB_STEP_SUMMARY
